name: Java CI with Gradle

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --info --stacktrace

      - name: Upload build jar
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: build/libs/*.jar